.TH RENDERA 1
.SH NAME
rendera \- A painting program.
.SH SYNOPSIS
.B rendera
[OPTIONS]
.IR file ...
.SH DESCRIPTION
.B rendera
Rendera is a painting program suitable for photo-retouching, seamless tile production, and colorizing black-and-white photographs.
.SH OPTIONS
.TP
.BR \-\-help
.RS
Shows command line options.
.RE
.TP
.BR \-\-theme =\fIdark\fR
Enables the dark theme, which is the default.
.TP
.BR \-\-theme =\fIlight\fR
Enables the light theme.

